version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  front-end: # name of the first service
    build: front-end # specify the directory of the Dockerfile
    volumes:
      - ./front-end:/usr/src/app
    ports:
      - "4200:4200" # specify port forewarding

  back-end: #name of the second service
    build: back-end # specify the directory of the Dockerfile
    volumes:
      - ./back-end:/usr/src/app
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database # link this service to the database service

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding